services:
  redis:
    image: redis:7.0.5
    container_name: ecommerce-redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - ./redis/data:/data
      # - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server
    networks:
      - ecommerce-network

  mysql:
    image: mysql:8.0
    container_name: commerce-mysql
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: application
      MYSQL_DATABASE: ecommerce
      TZ: UTC
    volumes:
      - ./data/mysql/:/var/lib/mysql
    networks:
      - default

networks:
  ecommerce-network:
    driver: bridge
